### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by pradyunsg** [autophagy/insegel#5]
Is this theme usable by simply adding `html_theme = "insegel"` to the conf.py for a Sphinx project?

**Comment by autophagy** [comment]
Hi @pradyunsg - sorry for the late reply!

You first have to install the package via pip, usually by ``pip install insegel`` or by adding insegel to your projects requirements.txt or setup.py file (however you're managing documentation dependencies.

Then, yes, just adding the ``html_theme`` string to conf.py should work.

**Comment by pradyunsg** [comment]
Thanks for the response (and happy new year)!

I figured it out and added the theme on sphinx-themes.org (let me know if you don't want it there). Beyond that, it'd be nice to have this information in the README, but that's upto you. :)

**Comment by autophagy** [comment]
Good point! I'll add the info to the readme. :+1:
