### ISSUE TITLE
Logo Selection 

### ISSUE THREAD

**Issue by VHchavez** [autophagy/insegel#7]
Hello Mika, 
I am interested in using your theme. I have been able to install it and use it in my project. 
I noticed that the release for 1.1.0 mentioned the ability to change the logo. I have unfortunately been unable to use that option in my config.py file. 
Is there an appropriate way of changing it, 

Thanks a lot!

**Comment by BadriAhmed** [comment]
I know it is not the solution you look for, but a temporary solution is to change the logo.svg file under _build/html/_static/img, or even change the logo name in your index.html

**Comment by autophagy** [comment]
Hi @VHchavez - sorry for the slow response on this. I verified that this still seems to work.

With this config.py:

```
source_suffix = '.rst'
master_doc = 'index'
html_theme = 'insegel'
html_theme_options = {

}

html_logo = "github.png"
```

![logo](https://user-images.githubusercontent.com/12958979/123228153-8f2ac700-d4d5-11eb-923f-04afc738c8b8.png)

The path to the logo file has to be **relative to the config.py** file. In the above case, `github.png` is in the same directory as the `config.py` file. Could you verify that that is the case?

**Comment by VHchavez** [comment]
This worked great. Thanks! :)
Is there any option to resize the logo?
