### ISSUE TITLE
Incompatibility with nbsphinx.

### ISSUE THREAD

**Issue by larsgeb** [autophagy/insegel#9]
Hi there, lovely theme! 

Unfortunately it doesn't seem to work nicely with nbsphinx, a tool to include Jupyter Notebooks in Sphinx generated documentation. Specifically, `<pre>` elements (products of Python warnings) don't overflow nicely.

![Screen Shot 2021-06-28 at 15 18 57](https://user-images.githubusercontent.com/21038893/123643172-6895c480-d824-11eb-9f72-7afbc7f7abba.png)

Fixed by adding the following CSS:
```
pre {
white-space: pre-wrap;
}
```
I'll try to make a PR for this.

**Comment by autophagy** [comment]
This was addressed with #10 - but i'll leave this open until I create a new release containing the fix. :slightly_smiling_face:

**Comment by autophagy** [comment]
This has been released with 1.2.0.
